
CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL
);

INSERT INTO messages (content) VALUES 
('A faithful friend is a strong defense.'),
('A fresh start will put you on your way.'),
('A golden egg of opportunity falls into your lap this month.'),
('A lifetime of happiness lies ahead of you.'),
('A pleasant surprise is waiting for you.'),
('A smile is your passport into the hearts of others.'),
('A smooth long journey! Great expectations.'),
('Adventure awaits those who seek it.'),
('An inch of time is an inch of gold.'),
('Be not afraid of growing slowly, be afraid only of standing still.'),
('Be patient! The best things happen unexpectedly.'),
('Believe in yourself and others will too.'),
('Change is happening in your life, so go with the flow!'),
('Curiosity kills boredom. Nothing can kill curiosity.'),
('Do not let ambitions overshadow small success.'),
('Do not make extra work for yourself.'),
('Don’t just think, act!'),
('Every flower blooms in its own sweet time.'),
('Failure is the chance to do better next time.'),
('Fortune favors the bold.'),
('From now on your kindness will lead you to success.'),
('Good news will come to you by mail.'),
('Happiness begins with facing life with a smile and a wink.'),
('Happiness will come to you when you least expect it.'),
('Happy life is just in front of you.'),
('If you continually give, you will continually have.'),
('If your desires are not extravagant, they will be granted.'),
('Imagination rules the world.'),
('In the middle of every difficulty lies opportunity.'),
('It is now, and in this world, that we must live.'),
('Keep your face to the sunshine and you will never see the shadows.'),
('Let the deeds speak.'),
('Life consists not in holding good cards but in playing those you hold well.'),
('Life is like a mirror; smile at it and it smiles back at you.'),
('Love is as necessary to human beings as food and shelter.'),
('Love truth, but pardon error.'),
('Make all you can, save all you can, give all you can.'),
('Make each day your masterpiece.'),
('Nature, time, and patience are three great physicians.'),
('Never give up. You are not a failure if you don’t give up.'),
('No act of kindness, no matter how small, is ever wasted.'),
('Nothing is so much to be feared as fear.'),
('One small positive thought can change your whole day.'),
('Our deeds determine us, as much as we determine our deeds.'),
('Remember to share good fortune as well as bad with your friends.'),
('Seek out the significance of your problem at this time. Try to understand.'),
('Success is getting what you want. Happiness is liking what you get.'),
('Take time to enjoy the simple things in life.'),
('The best is yet to come.'),
('The secret of staying young is good health and lying about your age.');

